version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    working_dir: /app
    volumes:
      - ./web:/app
    networks:
      - app_net
    ports:
      - "8000:5000"
    entrypoint: ["python", "app.py"]

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:  
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app_net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"    # SSH access
    volumes:
      - gitea_data:/data
    environment:
      USER_UID: 1000
      USER_GID: 1000
    networks:
      - app_net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=true
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - app_net

volumes:
  gitea_data:
  sonarqube_data:
  sonarqube_extensions:

networks:
  app_net:
    driver: bridge

# sqp_bdf57983d2f0450381ea2b603c99094cd05278c8
# Admin123!123


