version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    working_dir: /app
    volumes:
      - ./web:/app
    networks:
      - app_net
    ports:
      - "8000:5000"
    entrypoint: ["python", "app.py"]
    
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app_net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000"  # Web UI
      - "2222:22"    # SSH access
    volumes:
      - gitea_data:/data
    environment:
      USER_UID: 1000
      USER_GID: 1000
    networks:
      - app_net

volumes:
  gitea_data:

networks:
  app_net:
    driver: bridge



